#if !canImport(ObjectiveC)
import XCTest

extension DiffMatchPatchTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DiffMatchPatchTests = [
        ("testBisect", testBisect),
        ("testCleanupMerge", testCleanupMerge),
        ("testCommonPrefix", testCommonPrefix),
        ("testCommonSuffix", testCommonSuffix),
        ("testConstruction", testConstruction),
        ("testHalfMatch", testHalfMatch),
        ("testSimpleCases", testSimpleCases),
    ]
}

extension SpeedTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpeedTests = [
        ("testSpeed", testSpeed),
    ]
}

extension StringExtensionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StringExtensionTests = [
        ("testSimpleCases", testSimpleCases),
    ]
}

extension UtilitiesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UtilitiesTests = [
        ("testDifferenceEndsWith", testDifferenceEndsWith),
        ("testDifferenceStartsWith", testDifferenceStartsWith),
        ("testFloordiv", testFloordiv),
        ("testMergeConsecutive", testMergeConsecutive),
        ("testSubstring", testSubstring),
        ("testSubstringPartition", testSubstringPartition),
        ("testSubstringSingleIndex", testSubstringSingleIndex),
        ("testSubstringSuffix", testSubstringSuffix),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DiffMatchPatchTests.__allTests__DiffMatchPatchTests),
        testCase(SpeedTests.__allTests__SpeedTests),
        testCase(StringExtensionTests.__allTests__StringExtensionTests),
        testCase(UtilitiesTests.__allTests__UtilitiesTests),
    ]
}
#endif
